# Generated by Django 4.2.7 on 2024-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="middle_name",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="По-батькові"
            ),
        ),
    ]
