repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
#    - id: pretty-format-json
    - id: check-merge-conflict
#    - id: check-json
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
#-   repo: https://github.com/pre-commit/mirrors-csslint
#    rev: v1.0.5
#    hooks:
#    -   id: csslint