# some students

import datetime

students_list_data = (
    {
        "id": 1,
        "first_name": "Дмитро",
        "last_name": "Волошко",
        "ticket": 235,
        "image": "img/image_1.jpeg",
    },
    {
        "id": 2,
        "first_name": "Ігор",
        "last_name": "Шевченко",
        "ticket": 2123,
        "image": "/img/image_2.jpg",
    },
    {
        "id": 3,
        "first_name": "Володимир",
        "last_name": "Строцяк",
        "ticket": 6,
        "image": "/img/image_3.jpeg",
    },
)

groups_list_data = (
    {"id": 1, "name": "Мтм-21", "leader": {"id": 1, "name": "Літвінов Дмитро"}},
    {"id": 2, "name": "Мтм-22", "leader": {"id": 2, "name": "Віталій Подоба"}},
)
# some people
people_datta = (
    {
        "id": 1,
        "firstname": "Emil",
        "lastname": "Refsnes",
        "phone": 5551234,
        "joined_date": datetime.date(2022, 1, 5),
    },
    {
        "id": 2,
        "firstname": "Tobias",
        "lastname": "Refsnes",
        "phone": 5557777,
        "joined_date": datetime.date(2021, 4, 1),
    },
    {
        "id": 3,
        "firstname": "Linus",
        "lastname": "Refsnes",
        "phone": 5554321,
        "joined_date": datetime.date(2021, 12, 24),
    },
    {
        "id": 4,
        "firstname": "Lene",
        "lastname": "Refsnes",
        "phone": 5551234,
        "joined_date": datetime.date(2021, 5, 1),
    },
    {
        "id": 5,
        "firstname": "Stalikken",
        "lastname": "Refsnes",
        "phone": 5559876,
        "joined_date": datetime.date(2022, 9, 29),
    },
)
test_data = {
    "Lorem": "Ipsum",
    "is": "simply",
    "dummy": "text",
    "of": "Lorem",
    "printing": "and",
    "typesetting": "industry.",
    "has": "survived",
    "the": "1960s",
    "standard": "dummy",
    "text": "ever",
    "since": "the",
    "1500s,": "when",
    "an": "unknown",
    "printer": "took",
    "a": "galley",
    "and": "more",
    "it": "to",
    "make": "a",
    "type": "specimen",
    "book.": "It",
    "not": "only",
    "five": "centuries,",
    "but": "also",
    "into": "electronic",
    "typesetting,": "remaining",
    "essentially": "unchanged.",
    "It": "was",
    "popularised": "in",
    "with": "the",
    "release": "of",
    "Letraset": "sheets",
    "containing": "Lorem",
    "Ipsum": "passages,",
    "recently": "with",
    "desktop": "publishing",
    "software": "like",
    "Aldus": "PageMaker",
    "including": "versions",
}

test_data_2 = {
    "It": "is",
    "a": "search",
    "established": "fact",
    "that": "a",
    "reader": "962435",
    "be": "distracted",
    "by": "accident,",
    "readable": "English.",
    "of": "337536",
    "page": "editors",
    "looking": "at",
    "its": "layout.",
    "The": "point",
    "Lorem": "Ipsum",
    "is": "that",
    "it": "has",
    "normal": "distribution",
    "as": "their",
    "to": "using",
    "'Content": "here,",
    "content": "here',",
    "making": "107473",
    "look": "like",
    "Many": "98952",
    "publishing": "packages",
    "and": "785022",
    "now": "use",
    "default": "960399",
    "text,": "and",
    "for": "'lorem",
    "ipsum'": "will",
    "uncover": "310529",
    "web": "sites",
    "still": "581067",
    "their": "infancy.",
    "Various": "versions",
    "have": "298540",
    "over": "the",
    "years,": "sometimes",
    "sometimes": "652980",
    "purpose": "308189",
    "humour": "and",
    "the": "like).",
}
